baseURL = "snailshell.github.io"
title = "蜗庐"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "zh-cn"

[params.info]
description = "尽日方寸中，澹然无所欲。"
title404 = "404"

[params.assets]
favicon = "favicon.ico"
customCSS = ["dist/zoom.css"]
customJS = ["dist/zoom-vanilla.min.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Snail Shell"
startYear = ""
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, 01 02"
listDateFormat = "2006, 01 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = true
showReadingTime = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = ""
facebook = ""
github = ""
instagram = ""
linkedin = ""
twitter = ""

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.zh-cn]
lang = "zh-cn"
languageName = "Simplified Chinese"
weight = 1
